import { notFound } from 'next/navigation';
import React from 'react';
import { getVirusesInsecure } from '../../database/viruses';
import { getCookie } from '../../util/cookies';
import { parseJson } from '../../util/json';

export const metadata = {
  title: 'Cart',
  description: 'Generated by create next app',
};

export default async function CartPage() {
  const cartCookie = await getCookie('cart');
  const cartItems = parseJson(cartCookie) || [];
  const viruses = await getVirusesInsecure();

  // const displayCart = cart.map((quantity) => {
  //   return;
  // });

  // getVirus(cartItem.id) {
  //   return
  // }

  // const total = cartItems((cartItem) => {
  //   return viruses[cartItem.id - 1].price;
  // });

  // const calculateSubtotal = (id, quantity) => {
  //   return cartItem.id * cartItem.quantity;
  // };s

  // const subtotal = cartItems.forEach(cartItem.id);
  // console.log(`subtotal`, subtotal);

  // console.log(`cartItems:`, cartItems);
  // let firstArray = [1, 2, 3];
  // let secondArray = [];
  // firstArray.forEach((element) => {
  //   secondArray.push(element.id);
  // });

  // subtotals.push(8);
  // subtotals = cartItems;
  // subtotals = cartItems.forEach((element) => {
  //   subtotals.push('3');
  //   // numCallbackRuns++;
  // });
  // subtotals();
  // console.log(`firstArray`, firstArray);
  // console.log(`secondArray`, secondArray);

  // if (!virusToUpdate) {
  //   cart.push({ id: virusId, quantity: quantity });
  // } else {
  //   virusToUpdate.quantity += quantity;
  // }

  return (
    <>
      <h1>Cart</h1>

      <div className="cart">
        {cartItems.map((cartItem) => {
          return (
            <div key={`cartItemId-${cartItem.id}`} className="cartItem">
              <h2>Product ID: {cartItem.id}</h2>
              <div>Name: {viruses[cartItem.id - 1].virusName}</div>
              <div>Price: {viruses[cartItem.id - 1].price}</div>
              {/* <div>{viruses[getVirus(`${cartItem.id}`)].name}</div> */}
              {/* <div>Name = {viruses.getVirus(`${cartItem.id}`)}</div> */}
              <img
                alt={viruses[cartItem.id - 1].virusName}
                src={`/viruses/${viruses[cartItem.id - 1].image}`}
                // className="detailImage"
              />
              <h3>Quantity: {cartItem.quantity}</h3>
              <div>
                Total for this item:
                {parseInt(viruses[cartItem.id - 1].price) * cartItem.quantity}
                {/* {Number(viruses[cartItem.id - 1].price)} */}
                {/* {Number(cartItem.quantity) *
                  Number(viruses[cartItem.id - 1].price)} */}
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
}
