export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return (
    <>
      <h1>This is my about page</h1>
      <p>This is my about text</p>
    </>
  );
}
