import './globals.css';
import localFont from 'next/font/local';
import Image from 'next/image';
import Link from 'next/link';
import { getCookie } from '../util/cookies';
import { parseJson } from '../util/json';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });
const groteskGras = localFont({
  src: './fonts/Grotesk-04Gras.woff',
  variable: '--font-grotesk-gras',
  weight: '900',
});
const groteskMince = localFont({
  src: './fonts/Grotesk-02Mince.woff',
  variable: '--font-grotesk-mince',
  weight: '100',
});
const groteskRegular = localFont({
  src: './fonts/Grotesk-03Regular.woff',
  variable: '--font-grotesk-regular',
  weight: '400',
});
const ddin = localFont({
  src: './fonts/D-DIN.woff',
  variable: '--font-ddin',
  weight: '300',
});

export const metadata = {
  title: {
    default: 'Home | Vector',
    template: '%s | Vector',
  },

  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cartCookie = await getCookie('cart');
  const cartItems = parseJson(cartCookie) || [];

  // const totalCartItems = cartItems.map((item) => {
  //   return item.quantity
  // })

  const totalCartItems = cartItems.reduce((acc, item) => {
    return (acc += item.quantity);
  }, 0);

  return (
    <html lang="en">
      <body
        className={`${groteskGras.variable} ${groteskMince.variable} ${groteskRegular.variable} ${ddin.variable}`}
      >
        <header>
          <Link href="/">
            <h2>Vector</h2>
          </Link>
          <nav>
            <div>
              <Link href="/viruses">Viruses</Link>
            </div>
            <Link href="/about">About</Link>
            <Link href="/cart" data-test-id="cart-link">
              Cart:{' '}
              <span data-test-id="cart-count">
                {`[${totalCartItems ? totalCartItems : 'empty'}]`}
              </span>
            </Link>
            <Link href="/checkout">Checkout</Link>
            {/* <Image
                alt="vector"
                src="/vector-logo.webp"
                width="300"
                height="300"
              /> */}
          </nav>
        </header>
        <main>{children}</main>
        {/* <footer>Footer</footer> */}
      </body>
    </html>
  );
}
