export const metadata = {
  title: 'Checkout',
  description: 'Generated by create next app',
};

export default function CheckoutPage() {
  return (
    <>
      <h1>Checkout</h1>
      <p>This is the checkout content.</p>
    </>
  );
}
